site_name: repro-screener

nav:
  - Home: index.md
  - Usage: usage.md
  - Case studies: case-studies.md
  - Todo: todo.md
  - Docstrings: docstrings.md
  - References: z_references.md

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  # font: 
  #   text: Roboto
  #   code: Roboto Mono
  features:
    - toc.integrate
    - navigation.top
    - navigation.tracking




plugins:
  - search
  - mkdocstrings:

  - bibtex:
      bib_file: "references.bib"
      csl_file: "https://raw.githubusercontent.com/citation-style-language/styles/master/acm-sig-proceedings.csl"
      # cite_inline: True



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - admonition
  - pymdownx.details
